name: odoo_timer
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  flutter_platform_widgets: ^6.1.0
  flutter_native_splash: ^2.3.13
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  overlay_support: ^2.1.0
  responsive_builder:
  responsive_sizer:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/Inter/Inter-Regular.ttf
    - assets/fonts/Roboto/Roboto-Regular.ttf
    - assets/images/odoo_text.png
    - assets/images/splash_screen_background.png

flutter_native_splash:
  background_image: "assets/images/splash_screen_background.png"
  web: false


